version: "3.9"
services:
  app:
    build: .
    container_name: jobtracker-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
    networks:
      - jobtracker-net

  db:
    image: postgres:16-alpine
    container_name: jobtracker-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobtracker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - jobtracker-net

volumes:
  pgdata:

networks:
  jobtracker-net:
